services:
  postgres:
    image: postgres:latest
    container_name: lab-2-tools-postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5434:5432"
    restart: unless-stopped
    networks:
      - configuration-service-network
  
  postgres2:
    image: postgres:latest
    container_name: lab-2-tools-postgres2
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5433:5432"
    restart: unless-stopped
    networks:
      - configuration-service-network
  
  
  configuration-service:
    image: ghcr.io/is-csms-y26/lab-2-tools:master
    platform: linux/amd64
    container_name: configuration-service
    networks:
      - configuration-service-network
    ports:
      - '8080:8080'
    environment:
      Persistence__Postgres__Host: postgres

networks:
  configuration-service-network:
    driver: bridge